
import _cons from './cons';
import _car from './car';
import _cdr from './cdr';
import _print from './print';
import _equal from './equal';
import _pair from './pair';
import compose from '../fun/compose';

export const cons = _cons;
export const car = _car;
export const cdr = _cdr;
export const caar = compose(car, car);
export const cadr = compose(cdr, car);
export const cdar = compose(car, cdr);
export const cddr = compose(cdr, cdr);
export const caaar = compose(car, compose(car, car));
export const caadr = compose(cdr, compose(car, car));
export const cadar = compose(car, compose(cdr, car));
export const caddr = compose(cdr, compose(cdr, car));
export const cdaar = compose(car, compose(car, cdr));
export const cdadr = compose(cdr, compose(car, cdr));
export const cddar = compose(car, compose(cdr, cdr));
export const cdddr = compose(cdr, compose(cdr, cdr));
export const caaaar = compose(car, compose(car, compose(car, car)));
export const caaadr = compose(cdr, compose(car, compose(car, car)));
export const caadar = compose(car, compose(cdr, compose(car, car)));
export const caaddr = compose(cdr, compose(cdr, compose(car, car)));
export const cadaar = compose(car, compose(car, compose(cdr, car)));
export const cadadr = compose(cdr, compose(car, compose(cdr, car)));
export const caddar = compose(car, compose(cdr, compose(cdr, car)));
export const cadddr = compose(cdr, compose(cdr, compose(cdr, car)));
export const cdaaar = compose(car, compose(car, compose(car, cdr)));
export const cdaadr = compose(cdr, compose(car, compose(car, cdr)));
export const cdadar = compose(car, compose(cdr, compose(car, cdr)));
export const cdaddr = compose(cdr, compose(cdr, compose(car, cdr)));
export const cddaar = compose(car, compose(car, compose(cdr, cdr)));
export const cddadr = compose(cdr, compose(car, compose(cdr, cdr)));
export const cdddar = compose(car, compose(cdr, compose(cdr, cdr)));
export const cddddr = compose(cdr, compose(cdr, compose(cdr, cdr)));
export const print = _print;
export const equal = _equal;
export const pair = _pair;